name: Run Python Timer

on:
  workflow_dispatch: # 手动触发运行

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 运行 Python 脚本
        run: python run.py

      - name: 上传日志文件 time_log.txt
        uses: actions/upload-artifact@v4
        with:
          name: timer-log-file
          path: time_log.txt
